const fs = require("fs");
const path = require("path");

const SOURCE = path.resolve(
  __dirname,
  "../../mobile/androidApp/src/main/assets/emojis",
);
const DEST = path.resolve(__dirname, "../assets/emojis");
const OUT = path.resolve(__dirname, "../src/domain/bacm/emojiAssets.generated.ts");

const FOLDERS = [
  "1f48c",
  "1f329_fe0f",
  "1f389_w_w_mqzx3u1111",
  "1f446",
  "1f614_w_w_mqzxkguj1c",
  "1f42c_w_w_mqzxq5g01i",
  "1f446_1f3fb_w_w_mqzwncruk",
  "glyphs_sparkles",
  "glyphs_arrows_round",
  "glyphs_comment_info",
  "glyphs_watch",
];

function copyFolderFiles(folder) {
  const srcDir = path.join(SOURCE, folder);
  const destDir = path.join(DEST, folder);
  fs.mkdirSync(destDir, { recursive: true });
  const entries = fs.readdirSync(srcDir, { withFileTypes: true });
  const copied = [];
  for (const entry of entries) {
    if (!entry.isFile()) continue;
    if (!entry.name.endsWith(".rgb565") && !entry.name.endsWith(".alpha")) continue;
    fs.copyFileSync(path.join(srcDir, entry.name), path.join(destDir, entry.name));
    copied.push(entry.name);
  }
  return copied;
}

function buildEntry(folder, files) {
  const has = (name) => files.includes(name);
  const staticImg = has("s.rgb565");
  const frameFiles = files
    .filter((f) => /^f\d{2}\.rgb565$/.test(f))
    .sort();

  const lines = [];
  lines.push(`  "${folder}": {`);
  if (staticImg) {
    lines.push(`    static: require("../../../assets/emojis/${folder}/s.rgb565"),`);
    lines.push(
      has("s.alpha")
        ? `    staticAlpha: require("../../../assets/emojis/${folder}/s.alpha"),`
        : `    staticAlpha: null,`,
    );
    lines.push(`    frames: [],`);
    lines.push(`    frameAlphas: [],`);
  } else {
    lines.push(`    static: null,`);
    lines.push(`    staticAlpha: null,`);
    const framesArr = frameFiles
      .map((f) => `require("../../../assets/emojis/${folder}/${f}")`)
      .join(", ");
    lines.push(`    frames: [${framesArr}],`);
    const alphaArr = frameFiles
      .map((f) => {
        const alphaName = f.replace(".rgb565", ".alpha");
        return has(alphaName)
          ? `require("../../../assets/emojis/${folder}/${alphaName}")`
          : "null";
      })
      .join(", ");
    lines.push(`    frameAlphas: [${alphaArr}],`);
  }
  lines.push(`  },`);
  return lines.join("\n");
}

function main() {
  fs.mkdirSync(DEST, { recursive: true });
  const entries = [];
  for (const folder of FOLDERS) {
    const files = copyFolderFiles(folder);
    entries.push(buildEntry(folder, files));
  }
  const header =
    "// Generated by scripts/gen-emojis.js. Do not edit by hand.\n" +
    "export type EmojiAssetEntry = {\n" +
    "  static: number | null;\n" +
    "  staticAlpha: number | null;\n" +
    "  frames: number[];\n" +
    "  frameAlphas: (number | null)[];\n" +
    "};\n\n" +
    "export const EMOJI_ASSETS: Record<string, EmojiAssetEntry> = {\n";
  const body = entries.join("\n");
  fs.writeFileSync(OUT, header + body + "\n};\n");
  console.log(`Generated ${OUT} with ${FOLDERS.length} folders`);
}

main();
